### ISSUE TITLE
06-authentication-and-authorization twitter login never sets IsAuthenticated

### ISSUE THREAD

**Issue by timcromarty** [dotnet-presentations/blazor-workshop#218] opened 2020-03-20 21:11 UTC
Trying to step through the Twitter Authentication instructions.  

- Click Login
- Redirects to Twitter to log in
- Redirects back to application, but Login Display still shows NotAuthorized view.

Have also tried adjusting launchsettings.json, using port 64589 or 64590 (unless I am adjusting launchsettings incorrectly). 

Any suggestions gratefully received

**Comment by danroth27** [comment] 2020-03-22 07:23
Can you confirm that you are running the Server project and not the Client project? The Server project should already have the correct ports setup in its launchSettings.json.

**Comment by timcromarty** [comment] 2020-03-22 21:05
Definitely running the server project (client project is not runnable).

Have tried save-points\07-javascript-interop to eliminate any local shanges, using today's latest version.  Still does not complete the login process. Sorry

**Comment by danroth27** [comment] 2020-03-23 03:39
@timcromarty Strange! I'm not able to reproduce any issue with the Twitter sign-in locally on my machine. The 07-javascript-interop save point works fine on my machine when I try to sign in.

Are there any errors in the ASP.NET Core logs in the server project? Are there any errors in the browser console?

**Comment by timcromarty** [comment] 2020-03-23 23:13
No errors that I can see.

Further investigation - I have run it on another (cleaner) machine and I can confirm it works correctly.  Must be something installed that is getting in the way.

Logs, debug enabled:

> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/user/signin  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path /user/signin does not match a supported file type
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 2 candidate(s) found for the request path '/user/signin'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server)' with route pattern 'user/signin' is valid for the request path '/user/signin'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/user/signin'
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server)'
> Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler: Debug: AuthenticationScheme: Cookies was not authenticated.
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server)'
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "SignIn", controller = "User"}. Executing controller action with signature System.Threading.Tasks.Task SignIn(System.String) on controller BlazingPizza.Server.UserController (BlazingPizza.Server).
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of authorization filters (in the following order): None
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of exception filters (in the following order): None
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter, Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Executing controller factory for controller BlazingPizza.Server.UserController (BlazingPizza.Server)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Executed controller factory for controller BlazingPizza.Server.UserController (BlazingPizza.Server)
> Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Debug: Attempting to bind parameter 'redirectUri' of type 'System.String' ...
> Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder: Debug: Could not find a value in the request with name '' for binding parameter 'redirectUri' of type 'System.String'.
> Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder: Debug: Done attempting to bind parameter 'redirectUri' of type 'System.String'.
> Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Debug: Done attempting to bind parameter 'redirectUri' of type 'System.String'.
> Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Debug: Attempting to validate the bound parameter 'redirectUri' of type 'System.String' ...
> Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Debug: Done attempting to validate the bound parameter 'redirectUri' of type 'System.String'.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executing action method BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server) - Validation state: Valid
> Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler: Debug: ObtainRequestToken
> Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler: Information: AuthenticationScheme: Twitter was challenged.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action method BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server), returned result Microsoft.AspNetCore.Mvc.EmptyResult in 1295.678ms.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server) in 1466.4387ms
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'BlazingPizza.Server.UserController.SignIn (BlazingPizza.Server)'
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 1611.2476ms 302 
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/signin-twitter?oauth_token=R052pQAAAAAAP3HDAAABcQmaHsA&oauth_verifier=o7j1D4PpRLCOmWfsQnY3Qo5nGnfnGsTZ  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path /signin-twitter does not match a supported file type
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/signin-twitter'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/signin-twitter'
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'Fallback {*path:nonfile}'
> Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler: Debug: ObtainAccessToken
> Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler: Information: AuthenticationScheme: Cookies signed in.
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 471.8245ms 302 
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/_framework/blazor.webassembly.js  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /_framework/blazor.webassembly.js.gz was not modified
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: Handled. Status code: 304 File: /_framework/blazor.webassembly.js.gz
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 29.1472ms 304 application/javascript
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/_framework/blazor.boot.json  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /_framework/blazor.boot.json.gz was not modified
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: Handled. Status code: 304 File: /_framework/blazor.boot.json.gz
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 15.5653ms 304 application/json
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /_framework/wasm/dotnet.3.2.0-preview2.20159.2.js.gz was not modified
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: Handled. Status code: 304 File: /_framework/wasm/dotnet.3.2.0-preview2.20159.2.js.gz
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 18.5078ms 304 application/javascript
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/user  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path /user does not match a supported file type
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 2 candidate(s) found for the request path '/user'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server)' with route pattern 'user' is valid for the request path '/user'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/user'
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server)'
> Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler: Debug: AuthenticationScheme: Cookies was not authenticated.
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server)'
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "GetUser", controller = "User"}. Executing controller action with signature BlazingPizza.UserInfo GetUser() on controller BlazingPizza.Server.UserController (BlazingPizza.Server).
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of authorization filters (in the following order): None
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of exception filters (in the following order): None
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter, Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Executing controller factory for controller BlazingPizza.Server.UserController (BlazingPizza.Server)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Executed controller factory for controller BlazingPizza.Server.UserController (BlazingPizza.Server)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executing action method BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server) - Validation state: Valid
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action method BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.1786ms.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: No information found on request to perform content negotiation.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: Attempting to select the first formatter in the output formatters list which can write the result.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
> Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Information: Executing ObjectResult, writing value of type 'BlazingPizza.UserInfo'.
> Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider: Debug: The response will be compressed with 'br'.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server) in 214.0467ms
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'BlazingPizza.Server.UserController.GetUser (BlazingPizza.Server)'
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 335.7504ms 200 application/json; charset=utf-8
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:64589/specials  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path /specials does not match a supported file type
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 2 candidate(s) found for the request path '/specials'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server)' with route pattern 'specials' is valid for the request path '/specials'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/specials'
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server)'
> Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler: Debug: AuthenticationScheme: Cookies was not authenticated.
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server)'
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "GetSpecials", controller = "Specials"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.Collections.Generic.List`1[BlazingPizza.PizzaSpecial]]] GetSpecials() on controller BlazingPizza.Server.SpecialsController (BlazingPizza.Server).
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of authorization filters (in the following order): None
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of exception filters (in the following order): None
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter, Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Executing controller factory for controller BlazingPizza.Server.SpecialsController (BlazingPizza.Server)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Debug: Executed controller factory for controller BlazingPizza.Server.SpecialsController (BlazingPizza.Server)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executing action method BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server) - Validation state: Valid
> Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.1.2 initialized 'PizzaStoreContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
> Microsoft.EntityFrameworkCore.Database.Command: Debug: Creating DbCommand for 'ExecuteReader'.
> Microsoft.EntityFrameworkCore.Database.Command: Debug: Created DbCommand for 'ExecuteReader' (4ms).
> Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opening connection to database 'main' on server 'pizza.db'.
> Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opened connection to database 'main' on server 'C:\Users\tim.cromarty\source\repos\dev\BlazorWorkshop2\save-points\07-javascript-interop\BlazingPizza.Server\pizza.db'.
> Microsoft.EntityFrameworkCore.Database.Command: Debug: Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
> SELECT "s"."Id", "s"."BasePrice", "s"."Description", "s"."ImageUrl", "s"."Name"
> FROM "Specials" AS "s"
> Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> SELECT "s"."Id", "s"."BasePrice", "s"."Description", "s"."ImageUrl", "s"."Name"
> FROM "Specials" AS "s"
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'PizzaStoreContext' started tracking 'PizzaSpecial' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
> Microsoft.EntityFrameworkCore.Database.Command: Debug: A data reader was disposed.
> Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closing connection to database 'main' on server 'C:\Users\tim.cromarty\source\repos\dev\BlazorWorkshop2\save-points\07-javascript-interop\BlazingPizza.Server\pizza.db'.
> Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closed connection to database 'main' on server 'pizza.db'.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action method BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 197.6544ms.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: No information found on request to perform content negotiation.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: Attempting to select the first formatter in the output formatters list which can write the result.
> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Debug: Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
> Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Information: Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[BlazingPizza.PizzaSpecial, BlazingPizza.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'.
> Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider: Debug: The response will be compressed with 'br'.
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server) in 338.6325ms
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'BlazingPizza.Server.SpecialsController.GetSpecials (BlazingPizza.Server)'
> Microsoft.EntityFrameworkCore.Infrastructure: Debug: 'PizzaStoreContext' disposed.
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 473.6535ms 200 application/json; charset=utf-8
>

**Comment by timcromarty** [comment] 2020-03-23 23:51
Resolved (sort of).  Problem related to something cached in Chrome (such as blazor.webassembly.js or other libs - log shows they are not being loaded.  Solution was to clear "All cookies and site data" from localhost sites in Chrome.  Now works fine.  Thanks anyway

**Comment by danroth27** [comment] 2020-03-23 23:52
Cool, I'm going to go ahead and close this issue then. Thanks for trying Blazor!

**Closed by danroth27** 2020-03-23 23:52 UTC
