### ISSUE TITLE
Upgrade to Server Side Blazor (.Net Core 3.0 Preview 4)

### ISSUE THREAD

**Issue by ADefWebserver** [dotnet-presentations/blazor-workshop#61] opened 2019-04-26 06:21 UTC
I created a server side version of this project (.Net Core 3.0 Preview 4) at:
https://github.com/ADefWebserver/BlazingPizza

**Comment by JeroenvdBurg** [comment] 2019-04-27 11:42
nice, thanks for sharing.

**Comment by danroth27** [comment] 2019-05-01 06:06
Closing as duplicate of #48

**Closed by danroth27** 2019-05-01 06:06 UTC
