### ISSUE TITLE
Website rendering on mobile devices

### ISSUE THREAD

**Issue by normandrews** [dotnet-presentations/blazor-workshop#155] opened 2019-09-28 22:10 UTC
This is a great demo application to learn the different blazor components. Will there be work done to make it responsive to different devices? The navbar doesn't collapse on smaller sizes nor does the content adjust accordingly when held vertically (rotated to landscape looks better). Attached is an example from Chrome (Toggle Device Toolbar)
![Annotation 2019-09-28 170942](https://user-images.githubusercontent.com/43594881/65822965-d60d5f00-e212-11e9-9969-fb2889f93052.jpg)

**Comment by normandrews** [comment] 2019-09-28 22:14
Looks like someone had beat me to it in June

https://github.com/dotnet-presentations/blazor-workshop/issues/98

**Comment by danroth27** [comment] 2019-09-30 15:55
Closing as duplicate of #98

**Closed by danroth27** 2019-09-30 15:55 UTC
